##-----------------------------------------------------------------------------
##
## File Name : makefile
##
## Creation Date : sam. 28 sept. 2013 22:18:06 CEST
##
## Modification Date : mar. 26 nov. 2013 18:15:04 CET
##
## Created By : ksej - www.rgba8.org
##
## Description :
##
##-----------------------------------------------------------------------------
INCLUDES     ?=
LIBRARIES    ?=
SOURCES      ?= main.cpp

