##-----------------------------------------------------------------------------
##
## File Name : makefile
##
## Creation Date : sam. 28 sept. 2013 22:18:06 CEST
##
## Modification Date : dim. 20 oct. 2013 17:43:32 CEST
##
## Created By : rgba8 (ksej) - www.empathy.fr
##
## Description :
##
##-----------------------------------------------------------------------------
INCLUDES     ?=
LIBRARIES    ?=
SOURCES      ?=

