##-----------------------------------------------------------------------------
##
## File Name : makefile
##
## Creation Date : sam. 28 sept. 2013 22:18:06 CEST
##
## Modification Date : lun. 18 nov. 2013 22:23:32 CET
##
## Created By : rgba8 (ksej) - www.empathy.fr
##
## Description :
##
##-----------------------------------------------------------------------------
INCLUDES     ?=
LIBRARIES    ?=
SOURCES      ?= main.cpp

