##-----------------------------------------------------------------------------
##
## File Name : makefile
##
## Creation Date : sam. 28 sept. 2013 22:18:06 CEST
##
## Modification Date : jeu. 03 oct. 2013 22:59:43 CEST
##
## Created By : rgba8 (ksej) - www.empathy.fr
##
## Description :
##
##-----------------------------------------------------------------------------
INCLUDES     ?=
LIBRARIES    ?=
DIRECTORIES  ?=
SOURCES      ?=

